import { Router } from 'express'
import { z } from 'zod'
import { pool } from '../db/pool.js'
import { asyncHandler, HttpError } from '../errors.js'
import { requireAuth } from '../middleware/auth.js'

const router = Router()
const id = z.string().uuid()
const questionInput = z.object({ type: z.enum(['multiple-choice', 'true-false', 'fill-blank', 'matching', 'short-answer', 'programming']), prompt: z.string().min(1).max(4000), explanation: z.string().max(4000).default(''), marks: z.number().int().positive().default(1), position: z.number().int().nonnegative().optional(), options: z.array(z.object({ text: z.string().min(1).max(500), correct: z.boolean().default(false) })).default([]) })
router.use(requireAuth)
router.use((request, _response, next) => request.auth?.role === 'teacher' ? next() : next(new HttpError(403, 'Teacher access required')))

async function ownedCourse(courseId: string, teacherId: string) {
    const result = await pool.query('SELECT id FROM courses WHERE id = $1 AND teacher_id = $2', [courseId, teacherId])
    if (!result.rows[0]) throw new HttpError(404, 'Course not found')
    return result.rows[0].id as string
}
async function ownedModule(moduleId: string, teacherId: string) {
    const result = await pool.query('SELECT m.id, m.course_id FROM modules m JOIN courses c ON c.id = m.course_id WHERE m.id = $1 AND c.teacher_id = $2', [moduleId, teacherId])
    if (!result.rows[0]) throw new HttpError(404, 'Module not found')
    return result.rows[0]
}
async function insertQuestion(table: 'questions' | 'test_questions' | 'exam_questions', answerTable: 'answers' | 'test_answers' | 'exam_answers', ownerColumn: 'quiz_id' | 'test_id' | 'exam_id', ownerId: string, input: z.infer<typeof questionInput>) {
    const question = await pool.query(`INSERT INTO ${table} (${ownerColumn}, type, prompt, explanation, marks, position) VALUES ($1, $2, $3, $4, $5, COALESCE($6, (SELECT COALESCE(max(position), -1) + 1 FROM ${table} WHERE ${ownerColumn} = $1))) RETURNING id, type, prompt, explanation, marks, position`, [ownerId, input.type, input.prompt, input.explanation, input.marks, input.position ?? null])
    for (const option of input.options) await pool.query(`INSERT INTO ${answerTable} (question_id, answer_text, is_correct) VALUES ($1, $2, $3)`, [question.rows[0].id, option.text, option.correct])
    return question.rows[0]
}

router.get('/dashboard', asyncHandler(async (request, response) => {
    const teacherId = request.auth!.userId
    const [courses, students, submissions, analytics] = await Promise.all([
        pool.query('SELECT c.id, c.title, c.status, s.name AS subject, count(DISTINCT e.student_id)::int AS students, count(DISTINCT l.id)::int AS lessons FROM courses c JOIN subjects s ON s.id = c.subject_id LEFT JOIN enrollments e ON e.course_id = c.id LEFT JOIN modules m ON m.course_id = c.id LEFT JOIN lessons l ON l.module_id = m.id WHERE c.teacher_id = $1 GROUP BY c.id, s.name ORDER BY c.updated_at DESC', [teacherId]),
        pool.query('SELECT count(DISTINCT e.student_id)::int AS total FROM enrollments e JOIN courses c ON c.id = e.course_id WHERE c.teacher_id = $1', [teacherId]),
        pool.query('SELECT count(*)::int AS pending FROM submissions sub JOIN assignments a ON a.id = sub.assignment_id WHERE a.teacher_id = $1 AND sub.score IS NULL', [teacherId]),
        pool.query('SELECT COALESCE(avg(qa.score), 0)::numeric(5,2) AS quiz_average, count(qa.id)::int AS quiz_attempts FROM quiz_attempts qa JOIN quizzes q ON q.id = qa.quiz_id JOIN courses c ON c.id = q.course_id WHERE c.teacher_id = $1', [teacherId]),
    ])
    response.json({ data: { courses: courses.rows, students: students.rows[0]?.total || 0, pendingSubmissions: submissions.rows[0]?.pending || 0, analytics: analytics.rows[0] } })
}))
router.get('/courses', asyncHandler(async (request, response) => { const result = await pool.query('SELECT c.id, c.title, c.description, c.difficulty, c.status, c.subject_id, s.name AS subject, count(DISTINCT e.student_id)::int AS students FROM courses c JOIN subjects s ON s.id = c.subject_id LEFT JOIN enrollments e ON e.course_id = c.id WHERE c.teacher_id = $1 GROUP BY c.id, s.name ORDER BY c.updated_at DESC', [request.auth!.userId]); response.json({ data: result.rows }) }))
router.post('/courses', asyncHandler(async (request, response) => { const input = z.object({ title: z.string().min(2).max(160), description: z.string().max(2000).default(''), subjectId: id, difficulty: z.string().max(80).default('Beginner'), educationLevelId: id.nullable().optional(), gradeId: id.nullable().optional(), programId: id.nullable().optional() }).parse(request.body); const result = await pool.query('INSERT INTO courses (teacher_id, subject_id, title, description, difficulty, status, education_level_id, grade_id, program_id) VALUES ($1, $2, $3, $4, $5, \'draft\', $6, $7, $8) RETURNING id, title, status', [request.auth!.userId, input.subjectId, input.title, input.description, input.difficulty, input.educationLevelId || null, input.gradeId || null, input.programId || null]); response.status(201).json({ data: result.rows[0] }) }))
router.patch('/courses/:courseId', asyncHandler(async (request, response) => { const courseId = await ownedCourse(String(request.params.courseId), request.auth!.userId); const input = z.object({ title: z.string().min(2).max(160).optional(), description: z.string().max(2000).optional(), difficulty: z.string().max(80).optional(), status: z.enum(['draft', 'pending', 'published', 'archived']).optional() }).parse(request.body); const result = await pool.query('UPDATE courses SET title = COALESCE($1, title), description = COALESCE($2, description), difficulty = COALESCE($3, difficulty), status = COALESCE($4, status), published_at = CASE WHEN $4 = \'published\' THEN now() ELSE published_at END WHERE id = $5 RETURNING id, title, description, difficulty, status', [input.title || null, input.description ?? null, input.difficulty || null, input.status || null, courseId]); response.json({ data: result.rows[0] }) }))
router.post('/courses/:courseId/modules', asyncHandler(async (request, response) => { const courseId = await ownedCourse(String(request.params.courseId), request.auth!.userId); const input = z.object({ title: z.string().min(1).max(160), position: z.number().int().nonnegative().optional() }).parse(request.body); const result = await pool.query('INSERT INTO modules (course_id, title, position) VALUES ($1, $2, COALESCE($3, (SELECT COALESCE(max(position), -1) + 1 FROM modules WHERE course_id = $1))) RETURNING id, title, position', [courseId, input.title, input.position ?? null]); response.status(201).json({ data: result.rows[0] }) }))
router.post('/modules/:moduleId/lessons', asyncHandler(async (request, response) => { const module = await ownedModule(String(request.params.moduleId), request.auth!.userId); const input = z.object({ title: z.string().min(1).max(160), content: z.unknown().default({}), durationMinutes: z.number().int().positive().default(1), position: z.number().int().nonnegative().optional() }).parse(request.body); const result = await pool.query('INSERT INTO lessons (module_id, title, content, duration_minutes, position) VALUES ($1, $2, $3, $4, COALESCE($5, (SELECT COALESCE(max(position), -1) + 1 FROM lessons WHERE module_id = $1))) RETURNING id, title, duration_minutes, position', [module.id, input.title, JSON.stringify(input.content), input.durationMinutes, input.position ?? null]); response.status(201).json({ data: result.rows[0] }) }))
router.post('/homework', asyncHandler(async (request, response) => { const input = z.object({ courseId: id, title: z.string().min(2).max(160), instructions: z.string().min(1).max(10000), dueAt: z.string().datetime(), totalMarks: z.number().int().positive().default(100), resources: z.array(z.unknown()).default([]) }).parse(request.body); await ownedCourse(input.courseId, request.auth!.userId); const result = await pool.query('INSERT INTO assignments (course_id, teacher_id, title, instructions, due_at, total_marks, resources) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, title, due_at, total_marks', [input.courseId, request.auth!.userId, input.title, input.instructions, input.dueAt, input.totalMarks, JSON.stringify(input.resources)]); response.status(201).json({ data: result.rows[0] }) }))
router.get('/homework', asyncHandler(async (request, response) => { const result = await pool.query('SELECT a.id, a.course_id, a.title, a.instructions, a.due_at, a.total_marks, c.title AS course FROM assignments a JOIN courses c ON c.id = a.course_id WHERE a.teacher_id = $1 ORDER BY a.due_at', [request.auth!.userId]); response.json({ data: result.rows }) }))
router.post('/quizzes', asyncHandler(async (request, response) => { const input = z.object({ courseId: id, lessonId: id.nullable().optional(), title: z.string().min(2).max(160), timeLimitSeconds: z.number().int().positive().nullable().optional() }).parse(request.body); await ownedCourse(input.courseId, request.auth!.userId); const result = await pool.query('INSERT INTO quizzes (course_id, lesson_id, title, time_limit_seconds) VALUES ($1, $2, $3, $4) RETURNING id, title, published', [input.courseId, input.lessonId || null, input.title, input.timeLimitSeconds || null]); response.status(201).json({ data: result.rows[0] }) }))
router.post('/quizzes/:quizId/questions', asyncHandler(async (request, response) => { const input = questionInput.parse(request.body); const owner = await pool.query('SELECT q.id FROM quizzes q JOIN courses c ON c.id = q.course_id WHERE q.id = $1 AND c.teacher_id = $2', [request.params.quizId, request.auth!.userId]); if (!owner.rows[0]) throw new HttpError(404, 'Quiz not found'); response.status(201).json({ data: await insertQuestion('questions', 'answers', 'quiz_id', String(request.params.quizId), input) }) }))
router.post('/tests', asyncHandler(async (request, response) => { const input = z.object({ courseId: id, title: z.string().min(2).max(160), instructions: z.string().max(10000).default(''), timeLimitSeconds: z.number().int().positive().nullable().optional() }).parse(request.body); await ownedCourse(input.courseId, request.auth!.userId); const result = await pool.query('INSERT INTO tests (course_id, title, instructions, time_limit_seconds) VALUES ($1, $2, $3, $4) RETURNING id, title, published', [input.courseId, input.title, input.instructions, input.timeLimitSeconds || null]); response.status(201).json({ data: result.rows[0] }) }))
router.post('/tests/:testId/questions', asyncHandler(async (request, response) => { const input = questionInput.parse(request.body); const owner = await pool.query('SELECT t.id FROM tests t JOIN courses c ON c.id = t.course_id WHERE t.id = $1 AND c.teacher_id = $2', [request.params.testId, request.auth!.userId]); if (!owner.rows[0]) throw new HttpError(404, 'Test not found'); response.status(201).json({ data: await insertQuestion('test_questions', 'test_answers', 'test_id', String(request.params.testId), input) }) }))
router.post('/exams', asyncHandler(async (request, response) => { const input = z.object({ courseId: id, title: z.string().min(2).max(160), instructions: z.string().max(10000).default(''), timeLimitSeconds: z.number().int().positive().default(60) }).parse(request.body); await ownedCourse(input.courseId, request.auth!.userId); const result = await pool.query('INSERT INTO exams (course_id, title, time_limit_seconds) VALUES ($1, $2, $3) RETURNING id, title, published', [input.courseId, input.title, input.timeLimitSeconds]); response.status(201).json({ data: result.rows[0] }) }))
router.post('/exams/:examId/questions', asyncHandler(async (request, response) => { const input = questionInput.parse(request.body); const owner = await pool.query('SELECT e.id FROM exams e JOIN courses c ON c.id = e.course_id WHERE e.id = $1 AND c.teacher_id = $2', [request.params.examId, request.auth!.userId]); if (!owner.rows[0]) throw new HttpError(404, 'Exam not found'); response.status(201).json({ data: await insertQuestion('exam_questions', 'exam_answers', 'exam_id', String(request.params.examId), input) }) }))
router.get('/submissions', asyncHandler(async (request, response) => { const result = await pool.query('SELECT s.id, s.assignment_id, s.student_id, s.content, s.score, s.feedback, s.submitted_at, a.title, c.title AS course, u.full_name AS student FROM submissions s JOIN assignments a ON a.id = s.assignment_id JOIN courses c ON c.id = a.course_id JOIN users u ON u.id = s.student_id WHERE a.teacher_id = $1 ORDER BY s.submitted_at DESC', [request.auth!.userId]); response.json({ data: result.rows }) }))
router.patch('/submissions/:submissionId/grade', asyncHandler(async (request, response) => { const input = z.object({ score: z.number().min(0), feedback: z.string().max(10000).default('') }).parse(request.body); const result = await pool.query('UPDATE submissions s SET score = $1, feedback = $2 FROM assignments a WHERE s.id = $3 AND a.id = s.assignment_id AND a.teacher_id = $4 RETURNING s.id, s.score, s.feedback', [input.score, input.feedback, request.params.submissionId, request.auth!.userId]); if (!result.rows[0]) throw new HttpError(404, 'Submission not found'); response.json({ data: result.rows[0] }) }))
router.get('/results', asyncHandler(async (request, response) => { const result = await pool.query(`SELECT 'quiz' AS type, q.title, qa.score, qa.submitted_at, u.full_name AS student FROM quiz_attempts qa JOIN quizzes q ON q.id = qa.quiz_id JOIN courses c ON c.id = q.course_id JOIN users u ON u.id = qa.student_id WHERE c.teacher_id = $1 UNION ALL SELECT 'test', t.title, ta.score, ta.submitted_at, u.full_name FROM test_attempts ta JOIN tests t ON t.id = ta.test_id JOIN courses c ON c.id = t.course_id JOIN users u ON u.id = ta.student_id WHERE c.teacher_id = $1 UNION ALL SELECT 'exam', e.title, ea.score, ea.submitted_at, u.full_name FROM exam_attempts ea JOIN exams e ON e.id = ea.exam_id JOIN courses c ON c.id = e.course_id JOIN users u ON u.id = ea.student_id WHERE c.teacher_id = $1 ORDER BY submitted_at DESC LIMIT 200`, [request.auth!.userId]); response.json({ data: result.rows }) }))
router.get('/analytics', asyncHandler(async (request, response) => { const result = await pool.query(`SELECT count(DISTINCT e.student_id)::int AS students, count(DISTINCT c.id)::int AS courses, COALESCE(avg(qa.score), 0)::numeric(5,2) AS average_score FROM courses c LEFT JOIN enrollments e ON e.course_id = c.id LEFT JOIN quizzes q ON q.course_id = c.id LEFT JOIN quiz_attempts qa ON qa.quiz_id = q.id WHERE c.teacher_id = $1`, [request.auth!.userId]); response.json({ data: result.rows[0] }) }))
router.get('/notifications', asyncHandler(async (request, response) => { const result = await pool.query('SELECT id, title, body, read_at, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT 50', [request.auth!.userId]); response.json({ data: result.rows }) }))
router.get('/ai/drafts', asyncHandler(async (request, response) => { const result = await pool.query('SELECT id, kind, title, content, status, created_at, updated_at FROM teacher_generated_content WHERE teacher_id = $1 ORDER BY updated_at DESC', [request.auth!.userId]); response.json({ data: result.rows }) }))
router.patch('/ai/drafts/:id', asyncHandler(async (request, response) => { const input = z.object({ title: z.string().min(2).max(500), markdown: z.string().min(1).max(50000) }).parse(request.body); const result = await pool.query(`UPDATE teacher_generated_content SET title = $1, content = jsonb_build_object('markdown', $2), updated_at = now() WHERE id = $3 AND teacher_id = $4 RETURNING id, kind, title, content, status, updated_at`, [input.title, input.markdown, request.params.id, request.auth!.userId]); if (!result.rows[0]) throw new HttpError(404, 'Draft not found'); response.json({ data: result.rows[0] }) }))
router.post('/ai/drafts/:id/publish', asyncHandler(async (request, response) => { const result = await pool.query(`UPDATE teacher_generated_content SET status = 'published', updated_at = now() WHERE id = $1 AND teacher_id = $2 RETURNING id, kind, title, content, status, updated_at`, [request.params.id, request.auth!.userId]); if (!result.rows[0]) throw new HttpError(404, 'Draft not found'); response.json({ data: result.rows[0] }) }))

export default router
