import { useState, type FormEvent } from 'react'
import { ArrowRight, BookOpen, CheckCircle2, ChevronRight, Clock3, GraduationCap, Search, Send, Settings2, Sparkles, Users } from 'lucide-react'
import { api, type EducationProfile, type LearningSummary } from '../lib/api'

type StudentCourse = { id: string | number; title: string; category: string; teacher: string; lessons: number; progress: number; difficulty: string; color: string; icon: string; description: string }
type StudentDashboardProps = { userName: string; courses: StudentCourse[]; subjects: Array<{ id: string | number; name: string; description: string }>; onExplore: () => void; onOpenCourse: (course: StudentCourse) => void; query: string; onQueryChange: (query: string) => void; summary: LearningSummary | null; profile: EducationProfile | null; onChangeLearningPath: () => void }

export default function StudentDashboard({ userName, courses, subjects, onExplore, onOpenCourse, query, onQueryChange, summary, profile, onChangeLearningPath }: StudentDashboardProps) {
    const [aiQuestion, setAiQuestion] = useState('')
    const [aiAnswer, setAiAnswer] = useState('')
    const [aiBusy, setAiBusy] = useState(false)
    const [aiError, setAiError] = useState('')
    const initials = userName.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()
    const activeCourses = courses.filter((course) => course.progress > 0 && course.progress < 100)
    const continueCourse = activeCourses[0] || courses[0]
    const quizScore = summary?.scores.find((item) => item.type === 'quiz')?.average_score || 0
    const learningPath = `${profile?.program_name || profile?.grade_name || profile?.education_level_name || 'Learning path'} · ${quizScore}% quiz average`

    async function askAi(event: FormEvent) {
        event.preventDefault()
        if (!aiQuestion.trim()) return
        setAiBusy(true); setAiError('')
        try { const result = await api.aiChat({ message: aiQuestion, educationLevel: profile?.education_level_name }); setAiAnswer(result.data.answer); setAiQuestion('') } catch (error) { setAiError(error instanceof Error ? error.message : 'Edusphere AI is temporarily unavailable.') } finally { setAiBusy(false) }
    }

    return <div className="student-dashboard">
        <header className="student-dashboard-header"><div><p className="student-kicker">Your learning path <span className="student-live-dot" /> {learningPath}</p><h1>Good morning, {userName.split(' ')[0] || 'student'}.</h1><p className="student-header-copy">Your dashboard shows published content assigned to your education profile.</p></div><div className="student-header-actions"><button className="student-icon-button" aria-label="Change learning path" title="Change learning path" onClick={onChangeLearningPath}><Settings2 size={19} /></button><button className="student-profile-button"><span className="student-avatar">{initials || 'S'}</span><span><strong>{userName}</strong><small>Student profile</small></span><ChevronRight size={16} /></button></div></header>
        <section className="student-command-row"><div className="student-ai-card"><div className="student-ai-orbit" aria-hidden="true"><Sparkles size={25} /></div><div className="student-ai-copy"><span className="student-section-label"><Sparkles size={13} /> Edusphere AI</span><h2>What are you curious about?</h2><p>Ask about your published learning content.</p><form className="student-ai-form" onSubmit={askAi}><input value={aiQuestion} onChange={(event) => setAiQuestion(event.target.value)} placeholder="Ask your learning assistant..." aria-label="Ask Edusphere AI" /><button disabled={aiBusy || !aiQuestion.trim()} aria-label="Ask Edusphere AI">{aiBusy ? <Clock3 size={17} /> : <Send size={17} />}</button></form>{aiError && <small className="student-ai-error">{aiError}</small>}{aiAnswer && <div className="student-ai-answer"><strong>Edusphere AI</strong><p>{aiAnswer}</p></div>}</div></div><div className="student-streak-card"><div className="student-streak-icon"><Clock3 size={20} /></div><span className="student-section-label">Your progress</span><strong>{summary?.learningStreak || 0} day streak</strong><p>{summary?.overallProgress || 0}% overall progress from recorded learning activity.</p></div></section>
        <div className="student-search-row"><label><Search size={18} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search published courses" aria-label="Search published courses" /></label><button className="student-explore-button" onClick={onExplore}>Explore subjects <ArrowRight size={16} /></button></div>
        {!courses.length ? <section className="student-section-block"><div className="student-empty-state"><BookOpen size={28} /><h2>No published lessons are available yet.</h2><p>Check back after your teacher or administrator publishes content for this learning path.</p><button className="student-explore-button" onClick={onChangeLearningPath}>Review learning path</button></div></section> : <>
            <section className="student-section-block"><div className="student-section-heading"><div><span className="student-section-label">My learning</span><h2>{continueCourse ? 'Pick up where you left off' : 'Published courses'}</h2></div><button onClick={onExplore}>View all learning <ArrowRight size={15} /></button></div>{continueCourse && <article className="student-continue-card" onClick={() => onOpenCourse(continueCourse)}><div className={`student-course-art ${continueCourse.color}`}><span>{continueCourse.icon}</span><em>Continue learning</em></div><div className="student-continue-body"><div><span>{continueCourse.category}</span><h3>{continueCourse.title}</h3><p>{continueCourse.teacher}</p></div><strong>{continueCourse.progress}%</strong><div className="student-progress"><i style={{ width: `${continueCourse.progress}%` }} /></div><small><BookOpen size={14} /> {continueCourse.lessons} published lessons</small></div></article>}</section>
            <section className="student-section-block"><div className="student-section-heading"><div><span className="student-section-label">My courses</span><h2>Published learning paths</h2></div><button onClick={onExplore}>Browse courses <ArrowRight size={15} /></button></div><div className="student-course-grid">{courses.slice(0, 6).map((course) => <article className="student-course-card" key={course.id} onClick={() => onOpenCourse(course)}><div className={`student-course-thumb ${course.color}`}><span>{course.icon}</span><small>{course.difficulty}</small></div><div className="student-course-card-body"><span>{course.category}</span><h3>{course.title}</h3><p>with {course.teacher}</p><div className="student-course-card-footer"><div className="student-progress"><i style={{ width: `${course.progress}%` }} /></div><strong>{course.progress}%</strong></div><small><BookOpen size={13} /> {course.lessons} published lessons</small></div></article>)}</div></section>
        </>}
        <section className="student-two-column"><div className="student-panel"><div className="student-section-heading compact"><div><span className="student-section-label">Recent activity</span><h2>Recorded learning</h2></div></div><div className="student-lesson-list">{summary?.recentActivity?.slice(0, 6).map((activity) => <div className="student-lesson-row" key={`${activity.activity_type}-${activity.occurred_at}`}><span className="student-lesson-icon mint"><CheckCircle2 size={14} /></span><span><strong>{activity.title}</strong><small>{activity.activity_type}</small></span><ChevronRight size={16} /></div>)}{!summary?.recentActivity?.length && <p className="student-empty">No learning activity recorded yet.</p>}</div></div><div className="student-panel student-subject-panel"><div className="student-section-heading compact"><div><span className="student-section-label">Subjects</span><h2>Published subjects</h2></div><button onClick={onExplore} aria-label="View subjects"><ArrowRight size={15} /></button></div><div className="student-subject-list">{subjects.map((subject) => <button key={subject.id} onClick={onExplore}><span className="subject-dot sky">{subject.name.slice(0, 2)}</span><span><strong>{subject.name}</strong><small>Published for your path</small></span><ChevronRight size={15} /></button>)}{!subjects.length && <small>No published subjects are available yet.</small>}</div></div></section>
        <section className="student-section-block student-work-section"><div className="student-section-heading"><div><span className="student-section-label">Your study desk</span><h2>Published homework</h2></div></div><div className="student-work-grid">{summary?.homework?.map((work) => <article className="student-work-card" key={work.id}><div className="student-work-mark sky"><CheckCircle2 size={17} /></div><div><span>{work.status}</span><h3>{work.title}</h3><p>Course content</p></div><small>{new Date(work.due_at).toLocaleDateString()}</small><ArrowRight size={15} /></article>)}{!summary?.homework?.length && <p className="student-empty">No published homework is available yet.</p>}</div></section>
        <footer className="student-dashboard-footer"><span><GraduationCap size={17} /> Learning is a journey, not a race.</span><span><Users size={14} /> EduSphere student workspace</span></footer>
    </div>
}
